metadata-files:
  - _core/metadata.yml
  
website:
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "PSYC121"
        contents: PSYC121/*
      - section: "PSYC122"
        contents: PSYC122/*

format:
  html: 
    include-in-header:
      - text: |
          <script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search Year 3";};</script>
